In [1]:
import numpy as np

# 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [2]:
array=np.arange(0,30).reshape(15,2)
array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

# 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [3]:
array=np.random.randint(0,120,60).reshape(5,4,3)
print(array.ndim)
print(array.shape)
print(array)

3
(5, 4, 3)
[[[ 41  52 107]
  [ 79  41 111]
  [  1  12  96]
  [ 54  82 106]]

 [[ 76  94 113]
  [ 96  13  83]
  [ 89  57  23]
  [102  85  89]]

 [[  9  45  76]
  [118  46 107]
  [116 106 119]
  [ 77 112  64]]

 [[ 68   0  49]
  [ 19  27   0]
  [106 109  55]
  [108  14   8]]

 [[ 84  97 110]
  [ 37  88  61]
  [ 16  92  64]
  [ 16  56 104]]]


# 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [4]:
array=np.array([[0,1],[2,3],[4,5],[6,7],[8,9],[0,1],[2,3],[4,5],[6,7],[8,9]])
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [5]:
array=array.reshape(-1)
print(array)
print(array.shape)
print(array.ndim)

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
(20,)
1


# İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [6]:
array=np.array([[0,1],[2,3],[4,5],[6,7],[8,9],[0,1],[2,3],[4,5],[6,7],[8,9]])
for i in range (len(array)):
    for j in range (len(array[i])):
        print(array[i][j])

0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9


In [7]:
for i in np.nditer(array):
    print(i)

0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9


# 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve 1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun. Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansınçıkartılsınçarpılsınbölünsün gibi.

In [8]:
array1=np.arange(5,35,5)
array2=np.arange(1,7)
print(array1/array2)
print(array1*array2)
print(array1+array2)
print(array1-array2)

[5. 5. 5. 5. 5. 5.]
[  5  20  45  80 125 180]
[ 6 12 18 24 30 36]
[ 4  8 12 16 20 24]


# 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin summeanmaxvarstd değerlerini inceleyin.

In [9]:
array=np.random.randint(0,101,10)
array

array([38, 53, 75, 34, 19, 87, 93, 73, 30, 65])

In [10]:
array.sum()

567

In [11]:
array.mean()

56.7

In [12]:
array.max()

93

In [13]:
array.var()

591.8100000000001

In [14]:
array.std()

24.327145331912664

# 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [15]:
array1=np.arange(0,20)
array2=np.arange(500,531)
array2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [16]:
np.concatenate([array1,array2],axis=0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

# 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [17]:
array1=np.arange(15,51)
array2=np.arange(10,101)
array3=np.concatenate([array1,array2],axis=0)
array3[25:51]=888
array3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

# 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [18]:
array1=np.arange(0,40).reshape(8,5)
array2=np.arange(320,360).reshape(8,5)
array3=np.concatenate([array1,array2],axis=0)
print(array3)
array3=np.concatenate([array1,array2],axis=1)
print(array3)

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]
[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]


# 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [19]:
array4=np.concatenate([array1,array2],axis=1)
array5=np.stack([array1,array2],axis=1)
print(array4)
print(array5)

[[  0   1   2   3   4 320 321 322 323 324]
 [  5   6   7   8   9 325 326 327 328 329]
 [ 10  11  12  13  14 330 331 332 333 334]
 [ 15  16  17  18  19 335 336 337 338 339]
 [ 20  21  22  23  24 340 341 342 343 344]
 [ 25  26  27  28  29 345 346 347 348 349]
 [ 30  31  32  33  34 350 351 352 353 354]
 [ 35  36  37  38  39 355 356 357 358 359]]
[[[  0   1   2   3   4]
  [320 321 322 323 324]]

 [[  5   6   7   8   9]
  [325 326 327 328 329]]

 [[ 10  11  12  13  14]
  [330 331 332 333 334]]

 [[ 15  16  17  18  19]
  [335 336 337 338 339]]

 [[ 20  21  22  23  24]
  [340 341 342 343 344]]

 [[ 25  26  27  28  29]
  [345 346 347 348 349]]

 [[ 30  31  32  33  34]
  [350 351 352 353 354]]

 [[ 35  36  37  38  39]
  [355 356 357 358 359]]]


# [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [20]:
array=np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(array==5)

(array([ 5, 13], dtype=int64),)

# Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [21]:
np.where(array%2==0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

# Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [22]:
np.where(array>4)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

# Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [23]:
np.where(array%5==0)

(array([ 1,  2,  5, 13], dtype=int64),)

# 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [24]:
np.random.randint(85,101)

94

# İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [25]:
array=np.random.randint(10,100,9).reshape(3,3)
array

array([[69, 52, 89],
       [47, 12, 43],
       [30, 42, 20]])

# 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [26]:
array=np.arange(35,60)
print(array)
np.random.choice(array)

[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59]


35

# Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [27]:
array = np.array([[3, 8, 10, 53, 3], 
                [3, 8, 10, 53, 8]])
array

array([[ 3,  8, 10, 53,  3],
       [ 3,  8, 10, 53,  8]])