In [1]:
import numpy as np

# Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin

In [2]:
array3B=np.array([[[17,26,43],[100,311,31]],[[56,28,64],[43,29,77]],[[88,23,99],[49,123,421]]])
print(array3B)
print(array3B.ndim)

[[[ 17  26  43]
  [100 311  31]]

 [[ 56  28  64]
  [ 43  29  77]]

 [[ 88  23  99]
  [ 49 123 421]]]
3


# 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.

In [3]:
array1B=np.arange(34,118,6)
array1B

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

# 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)

In [4]:
array91=np.linspace(50,500,91, dtype=int)
array91

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

# 100(10^2) ile 10000(10^5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.

In [5]:
array8=np.logspace(2,5,8)
array8

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

# 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.

In [6]:
array33=np.arange(0,9).reshape(3,3)
array33

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)

In [7]:
array0=np.zeros((6,6), dtype=int)
array0

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

# 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)

In [8]:
array1=np.ones((4,4), dtype=int)
array1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

# 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)

In [9]:
array88=np.eye(8, dtype=int)
array88

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

# 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)

In [10]:
array55=np.eye(5, dtype=int)*3
array55

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

# np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.

In [11]:
arrayrand=np.random.random(6)
arrayrand

array([0.68190103, 0.66462661, 0.68583935, 0.67046689, 0.07208473,
       0.55732637])

# np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.

In [12]:
arrayrandint=np.random.randint(50,101,(5,2))
print(arrayrandint)
print(arrayrandint.shape)

[[92 57]
 [51 80]
 [72 88]
 [99 89]
 [92 64]]
(5, 2)


# np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.

In [13]:
arrayint=np.random.randint(100,1000,(2,5,5))
print(arrayint)
print("Boyutu "+str(arrayint.ndim)+" Shape "+ str(arrayint.shape))

[[[562 706 856 998 739]
  [656 589 838 363 974]
  [804 648 698 399 306]
  [197 101 453 244 963]
  [874 944 388 393 848]]

 [[516 118 718 706 332]
  [623 764 636 601 607]
  [696 625 934 769 995]
  [886 319 148 428 243]
  [863 170 817 630 150]]]
Boyutu 3 Shape (2, 5, 5)


# np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

In [14]:
new_Array=np.random.randint(0,101,10)
print(new_Array)
print(new_Array.max())
print(new_Array.min())
print(new_Array.argmax())
print(new_Array.argmin())

[ 9 55 62 63 31 25 27 83  7 89]
89
7
9
8


# np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.

In [15]:
nparray=np.random.randint(300,501,(2,2,5))
print(nparray)

[[[419 393 494 486 307]
  [455 301 394 415 487]]

 [[443 445 407 473 475]
  [368 395 353 438 390]]]


In [16]:
print(nparray[1][1][0])
print(nparray[0][0][1])

368
393


# 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

In [17]:
array50=np.arange(0,51)
print(array50)
array50[20:35]=500
print(array50)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
